import type { ArchitectureData } from './components/ArchitectureMap'
import type { Archetype, ArchetypeParams } from './core/archetypes'
import type { Footprint } from './core/iso'
import { deriveArchetype, deriveHeight, deriveSize, packLayout } from './core/layout'
import type { ArchEdge, ArchFlow, ArchNode, Group } from './core/types'
import { MEASURED, UNCLAIMED } from './measured.generated'

/**
 * The authored half of the map: what exists, what it is called, what it does,
 * and which paths a payload actually travels. Counts, heights and footprints
 * come from the scanner and the packer — edit prose here, never numbers.
 *
 * Scope: the three v2 repos in full (phenix.ui, phenix.yard,
 * phenix.appointments). The v1 estate — USCS-FE, USCS-BE and its Oracle
 * database — is deliberately a single building.
 */

export const GROUPS: Group[] = [
  { id: 'browser', label: 'Front of house' },
  { id: 'platform', label: 'UI platform & gateway' },
  { id: 'yard', label: 'Yard service — phenix.yard' },
  { id: 'appointments', label: 'Appointments — phenix.appointments' },
  { id: 'outside', label: 'Outside world & v1' },
]

type AuthoredNode = Omit<ArchNode, 'archetype' | 'params' | 'height' | 'footprint' | 'count' | 'loc'> & {
  archetype?: Archetype
  params?: ArchetypeParams
  height?: number
  footprint?: Footprint
}

const AUTHORED: AuthoredNode[] = [
  /* ------------------------------------------------ Front of house */
  {
    id: 'ui-shell',
    archetype: 'cube',
    code: 'SH',
    name: 'Shell & chrome',
    role: 'the frame around every screen',
    group: 'browser',
    whatItDoes:
      'The Next.js app people actually visit. Owns the frame — sidebar navigation, warehouse ' +
      'selector, user menu, command palette — plus the login screen and the admin pages for ' +
      'feature flags and yard migration that belong to no sub-app.',
    howItsBuilt:
      'Sub-app code stays out of the shell: each route group holds [[thin wrappers]] re-exported ' +
      'from the sub-app packages and regenerated by a sync script, so one Next.js process serves ' +
      'what are effectively four applications.',
    files: [
      'phenix.ui/apps/shell/src/app/layout.tsx',
      'phenix.ui/apps/shell/src/components/AuthShell/AuthShell.tsx',
      'phenix.ui/apps/shell/src/components/WarehouseSelector/WarehouseSelector.tsx',
      'phenix.ui/apps/shell/src/app/admin/yard-migration/page.tsx',
    ],
    stack: ['Next.js 16', 'React 19', 'Tailwind 4', 'App Insights'],
  },
  {
    id: 'ui-yard-app',
    archetype: 'slab-stack',
    params: { levels: 5 },
    code: 'YA',
    name: 'Yard sub-app',
    role: "the yard operator's screens",
    group: 'browser',
    whatItDoes:
      'Gate arrival and departure forms and the live yard overlook — the whole yard drawn from ' +
      'one snapshot call, areas and spots and trailers with direction gauges.',
    howItsBuilt:
      'Every response is parsed with [[zod schemas]] generated (orval) from the yard service’s ' +
      'published OpenAPI specs, so a drifted contract fails loudly in development instead of ' +
      'rendering quietly wrong.',
    files: [
      'phenix.ui/apps/yard/src/pages/arrival/',
      'phenix.ui/apps/yard/src/pages/overlook/',
      'phenix.ui/apps/yard/src/generated/yard-api.zod.ts',
      'phenix.ui/apps/yard/orval.config.ts',
    ],
    stack: ['React Query', 'orval', 'zod'],
  },
  {
    id: 'ui-appointments-app',
    archetype: 'cube',
    code: 'AP',
    name: 'Appointments sub-app',
    role: 'the maintenance grid',
    group: 'browser',
    whatItDoes:
      'The appointments maintenance grid: search across warehouses with rich filters, then act — ' +
      'maintenance edits, notes, catalog-driven statuses.',
    howItsBuilt:
      'A thin client over the service’s search API: the mapping between filter UI and query ' +
      'params is isolated in one mapper module, and access is gated per warehouse by a ' +
      '[[feature-flag]] wrapper while the rollout is in progress.',
    files: [
      'phenix.ui/apps/appointments/src/components/AppointmentsMaintenanceTable/AppointmentsMaintenanceTable.tsx',
      'phenix.ui/apps/appointments/src/hooks/useMaintenanceAppointmentsSearch.ts',
      'phenix.ui/apps/appointments/src/lib/maintenanceFilterApiMappers.ts',
    ],
    stack: ['React Query'],
  },
  {
    id: 'ui-transaction-app',
    archetype: 'slab-stack',
    params: { levels: 5 },
    code: 'TX',
    name: 'Transaction history',
    role: 'the activity browser',
    group: 'browser',
    whatItDoes:
      'Browsing and drill-down over warehouse activity — the first screen ported from v1, plus a ' +
      'migration-state module tracking which warehouses have been cut over.',
    howItsBuilt:
      'Structured as self-contained modules with their own axios service layer and i18n bundle. ' +
      'It predates the newer sub-app conventions and reads differently from its siblings — the ' +
      'oldest building in the browser district.',
    files: [
      'phenix.ui/apps/transaction-history/src/modules/transaction-history/',
      'phenix.ui/apps/transaction-history/src/modules/migration-state/',
      'phenix.ui/apps/transaction-history/src/core/auth/',
    ],
    stack: ['axios', 'React Query'],
  },

  /* ------------------------------------------------ UI platform & gateway */
  {
    id: 'ui-bff',
    archetype: 'cube',
    code: 'BF',
    name: 'UI-BFF gateway',
    role: 'the server-side front door',
    group: 'platform',
    whatItDoes:
      'Next.js route handlers every browser call funnels through: /ui-bff/&lt;service&gt;/* is ' +
      'forwarded to the right backend on the internal network with the caller’s bearer token, ' +
      'so the browser only ever talks to its own origin.',
    howItsBuilt:
      'One generic passthrough covers five services from a single registry; the yard route is ' +
      'special-cased for development conveniences — canned fixtures, and a [[digit-sweep]] that ' +
      'fans one list call into many upstream pages and merges the results.',
    files: [
      'phenix.ui/apps/shell/src/app/ui-bff/serviceRegistry.ts',
      'phenix.ui/apps/shell/src/app/ui-bff/[svc]/[...path]/route.ts',
      'phenix.ui/apps/shell/src/app/ui-bff/yard/[...path]/route.ts',
      'phenix.ui/apps/shell/src/app/ui-bff/_proxy/proxy.ts',
    ],
    stack: ['Next.js route handlers'],
  },
  {
    id: 'ui-kit',
    code: 'UK',
    name: 'UI kit',
    role: 'the component library',
    group: 'platform',
    whatItDoes:
      'The shared component library: shadcn-style primitives plus the app chrome — sidebar, ' +
      'command palette, page templates, theming — that every sub-app renders through.',
    howItsBuilt:
      'Primitives follow the shadcn pattern but are rebuilt on [[Base UI]] rather than Radix. ' +
      'Every primitive carries a co-located story, which doubles as tamper-detection: running the ' +
      'stock shadcn generator would overwrite the customization and the missing story flags it.',
    files: [
      'phenix.ui/packages/ui/src/components/ui/',
      'phenix.ui/packages/ui/src/components/Form/',
      'phenix.ui/packages/shell-ui/src/components/AppSidebar/',
    ],
    stack: ['Base UI', 'Tailwind 4', 'Storybook'],
  },
  {
    id: 'ui-form-engine',
    archetype: 'slab-stack',
    params: { levels: 4 },
    code: 'FE',
    name: 'Form engine',
    role: 'the schema-driven form renderer',
    group: 'platform',
    whatItDoes:
      'Renders the yard’s data-entry forms from declarative schemas — field types, visibility ' +
      'rules, validation — instead of hand-built JSX per form.',
    howItsBuilt:
      'A plugin-and-rules architecture: field renderers and cross-field [[rules]] register against ' +
      'the schema walker, so gate arrival and departure share one vocabulary and a new form is ' +
      'mostly configuration.',
    files: [
      'phenix.ui/packages/form-engine/src/schema/',
      'phenix.ui/packages/form-engine/src/renderer/',
      'phenix.ui/packages/form-engine/src/rules/',
    ],
  },
  {
    id: 'ui-session-auth',
    archetype: 'cube',
    code: 'SA',
    name: 'Session & auth',
    role: 'the session gate',
    group: 'platform',
    whatItDoes:
      'Decides who is signed in and keeps them that way: the Keycloak OIDC dance, tokens in ' +
      'sessionStorage with a presence cookie the middleware checks, proactive refresh, and the ' +
      'session-scoped stores for feature flags, warehouse context and user preferences.',
    howItsBuilt:
      'An expired backend call comes back marked with a session-expired header and [[apiFetch]] ' +
      're-bootstraps once before failing — new tabs inherit a session without re-running the ' +
      'redirect. Feature flags are plain preference records, so they need no service of their own.',
    files: [
      'phenix.ui/packages/auth/src/service/authService.ts',
      'phenix.ui/packages/auth/src/utils/apiFetch.ts',
      'phenix.ui/packages/session/src/bootstrap/',
      'phenix.ui/apps/shell/src/proxy.ts',
    ],
    stack: ['Keycloak', 'OIDC'],
  },
  {
    id: 'ui-workshop',
    code: 'WS',
    name: 'The workshop',
    role: "the monorepo's toolbench",
    group: 'platform',
    whatItDoes:
      'Everything that builds and guards the monorepo rather than shipping in it: the ' +
      'wrapper-sync and check scripts, plop generators, the Playwright smoke suite, and the ' +
      'shared ESLint, TypeScript, Vitest and Storybook presets.',
    howItsBuilt:
      'Conventions are enforced rather than documented: sync-sub-app-wrappers regenerates the ' +
      'shell’s thin wrappers, check scripts fail CI when setup drifts, and [[boundary rules]] in ' +
      'ESLint keep sub-apps from importing each other.',
    files: [
      'phenix.ui/scripts/sync-sub-app-wrappers.ts',
      'phenix.ui/generators/plopfile.ts',
      'phenix.ui/e2e/',
      'phenix.ui/packages/eslint-config/app-boundaries.js',
    ],
    stack: ['Turborepo', 'pnpm', 'Playwright', 'plop'],
  },

  /* ------------------------------------------------ Yard service */
  {
    id: 'yard-core',
    archetype: 'slab-stack',
    params: { levels: 5 },
    code: 'YC',
    name: 'Lifted YMS core',
    role: 'the old engine, transplanted',
    group: 'yard',
    whatItDoes:
      'The yard domain as it arrived from the v1 monolith: gate, move and task services, form ' +
      'beans and Hibernate DAOs for arrivals, departures, moves, pre-cool, checks and transfers. ' +
      'Still the code that actually runs the yard.',
    howItsBuilt:
      '[[Lifted]] deliberately as-is — JSP-era controllers and DAOs included — so behavior stayed ' +
      'identical while everything around it modernizes. New faces are carved off it rather than ' +
      'rewriting it in place, which is why it is the biggest building on the map.',
    files: [
      'phenix.yard/src/main/java/com/uscs/phenix/yard/be/yms/service/ArrivalServiceImpl.java',
      'phenix.yard/src/main/java/com/uscs/phenix/yard/be/yms/',
      'phenix.yard/src/main/java/com/uscs/phenix/yard/be/location/',
    ],
    stack: ['Spring Boot', 'Hibernate'],
  },
  {
    id: 'yard-v2-api',
    code: 'YV',
    name: 'V2 API & slices',
    role: "the service's new face",
    group: 'yard',
    whatItDoes:
      'The new face of the service: REST controllers for the v2 UI (trailers, tasks, visitors, ' +
      'operations), the overlook snapshot, the read-only yard-setup API, and the package-by-feature ' +
      'domain slices — trailer, location, occupancy, driver, warehouse.',
    howItsBuilt:
      'The _v2 controllers are [[adapters]]: they translate clean REST into calls on the lifted ' +
      'core’s helpers instead of duplicating its logic. The contract is five published OpenAPI ' +
      'specs, the same files the UI generates its zod clients from.',
    files: [
      'phenix.yard/src/main/java/com/uscs/phenix/yard/be/_v2/yms/YardTrailerController.java',
      'phenix.yard/src/main/java/com/uscs/phenix/yard/overlook/OverlookController.java',
      'phenix.yard/src/main/java/com/uscs/phenix/yard/setup/YardSetupApiController.java',
      'phenix.yard/src/main/resources/openapi/yard-api.yaml',
    ],
    stack: ['Spring MVC', 'OpenAPI'],
  },
  {
    id: 'yard-seams',
    code: 'YS',
    name: 'Stubs & seams',
    role: 'the placeholder boundary',
    group: 'yard',
    whatItDoes:
      'The boundary with systems the yard does not own: appointment search assembled from the ' +
      'yard’s own gate and trailer state, and a stub layer standing in for warehouse master ' +
      'data, carriers, load tracker and shipment status.',
    howItsBuilt:
      'Every outbound dependency sits behind an interface whose default implementation is a local ' +
      'no-op — the service runs in isolation. A Feign-backed implementation is selected under the ' +
      '[[DISTRIBUTED]] profile as each real integration arrives.',
    files: [
      'phenix.yard/src/main/java/com/uscs/phenix/yard/appointments/impl/DefaultAppointmentSearchService.java',
      'phenix.yard/src/main/java/com/uscs/phenix/yard/stubs/appointment/',
      'phenix.yard/src/main/java/com/uscs/phenix/yard/stubs/carrier/',
    ],
    stack: ['Spring profiles', 'OpenFeign'],
  },
  {
    id: 'yard-events',
    archetype: 'cube',
    code: 'YE',
    name: 'Event publisher',
    role: 'the outbound event ramp',
    group: 'yard',
    whatItDoes:
      'Turns completed gate work into integration events — GateArrivalCompleted and ' +
      'GateDepartureCompleted — published to the yard.events topic for anyone downstream.',
    howItsBuilt:
      'Publication is transactional-then-async: Spring Modulith records the event in the database ' +
      'with the domain change, an [[externalizer]] ships it to Azure Service Bus afterwards, and a ' +
      'logging broker takes over when no bus is configured — local dev needs no Azure.',
    files: [
      'phenix.yard/src/main/java/com/uscs/phenix/yard/integration/event/YardEventExternalizer.java',
      'phenix.yard/src/main/java/com/uscs/phenix/yard/integration/event/ServiceBusYardEventBroker.java',
      'phenix.yard/src/main/java/com/uscs/phenix/yard/integration/event/GateArrivalEventPublisher.java',
    ],
    stack: ['Spring Modulith', 'Azure Service Bus'],
  },
  {
    id: 'yard-legacy-migration',
    archetype: 'cube',
    code: 'YL',
    name: 'Legacy bridge & migration',
    role: 'the Oracle-to-Postgres mover',
    group: 'yard',
    whatItDoes:
      'Moves warehouses from v1 to v2: reads yard topology, trailers, drivers and checks straight ' +
      'from the legacy Oracle schema, writes them to Postgres, and mints the sysid↔phenixId ' +
      'mappings that keep the two identity worlds in agreement.',
    howItsBuilt:
      'The [[ACL]] is the one sanctioned place sysids are translated — entity row and mapping row ' +
      'are written in a single transaction so the ids cannot drift. The orchestrator runs per ' +
      'warehouse with resumable state rows and per-table counts the admin screen reads back.',
    files: [
      'phenix.yard/src/main/java/com/uscs/phenix/yard/migration/MigrationOrchestrator.java',
      'phenix.yard/src/main/java/com/uscs/phenix/yard/legacy/OracleYardTopologyRepository.java',
      'phenix.yard/src/main/java/com/uscs/phenix/yard/acl/',
    ],
    stack: ['Spring JDBC', 'Oracle driver'],
  },
  {
    id: 'yard-db',
    archetype: 'low-slab',
    code: 'YD',
    name: 'Yard Postgres',
    role: "the yard's own database",
    group: 'yard',
    whatItDoes:
      'The service’s PostgreSQL schema plus its runtime configuration. V1 is the schema exactly ' +
      'as it was lifted from Oracle; every change since is its own migration.',
    howItsBuilt:
      '[[Flyway]] owns the schema — applied migrations are never edited, pre-Flyway databases are ' +
      'baselined at V1. The Modulith event-publication table lives here too, which is what makes ' +
      'event publishing survive restarts.',
    files: [
      'phenix.yard/src/main/resources/db/migration/V1__initial_schema.sql',
      'phenix.yard/src/main/resources/application.yaml',
    ],
    stack: ['PostgreSQL', 'Flyway'],
  },
  {
    id: 'yard-tests',
    archetype: 'slab-stack',
    params: { levels: 5 },
    code: 'YT',
    name: 'BDD test rig',
    role: 'the behavior harness',
    group: 'yard',
    whatItDoes:
      'Cucumber scenarios that drive yard capabilities end to end — arrival through departure — ' +
      'over HTTP against a real Postgres in Testcontainers, alongside the unit and integration suites.',
    howItsBuilt:
      'Scenarios are deliberately [[schema-agnostic]]: they act through endpoints and fixtures, ' +
      'never the database, so the schema can keep evolving underneath. Recording stubs observe ' +
      'outbound traffic, proving an appointment update happened while the integration is still stubbed.',
    files: [
      'phenix.yard/src/test/resources/features/',
      'phenix.yard/src/test/java/com/uscs/phenix/yard/bdd/',
      'phenix.yard/test-context/',
    ],
    stack: ['Cucumber', 'Testcontainers', 'JUnit'],
  },

  /* ------------------------------------------------ Appointments service */
  {
    id: 'appt-api',
    code: 'AA',
    name: 'Search & maintenance API',
    role: "the grid's backend",
    group: 'appointments',
    whatItDoes:
      'The REST backend for the appointments grid: search with rich filters, maintenance actions, ' +
      'notes, catalogs — delay reasons, load types, receipt statuses — and trailer load progress.',
    howItsBuilt:
      'Reads are [[dual-sourced]]: repositories come in oracle/ and postgres/ pairs and a ' +
      'data-source toggle decides per warehouse whether truth is still legacy Oracle or the ' +
      'migrated Postgres projection. The API shape stays identical either way.',
    files: [
      'phenix.appointments/src/main/java/com/uscs/phenix/appointments/maintenance/AppointmentMaintenanceController.java',
      'phenix.appointments/src/main/java/com/uscs/phenix/appointments/search/config/AppointmentDataSourceToggle.java',
      'phenix.appointments/src/main/java/com/uscs/phenix/appointments/maintenance/postgres/',
      'phenix.appointments/src/main/resources/openapi/appointments-api.yaml',
    ],
    stack: ['Spring Boot', 'Oracle driver', 'PostgreSQL'],
  },
  {
    id: 'appt-events',
    archetype: 'cube',
    code: 'AE',
    name: 'Yard event intake',
    role: 'the event-driven updater',
    group: 'appointments',
    whatItDoes:
      'Subscribes to yard.events and reacts to gate arrivals and departures: translates the ' +
      'event’s phenixIds back to legacy sysids and pushes the appointment update into v1, so ' +
      'the old system stays correct while it is still the system of record.',
    howItsBuilt:
      'The listener republishes each bus message as an internal Modulith event before doing any ' +
      'work; the durable registry then drives translation and the v1 call [[with retries]], so ' +
      'consuming the message is decoupled from the legacy call eventually landing.',
    files: [
      'phenix.appointments/src/main/java/com/uscs/phenix/appointments/messaging/YardEventListener.java',
      'phenix.appointments/src/main/java/com/uscs/phenix/appointments/messaging/GateArrivalHandler.java',
      'phenix.appointments/src/main/java/com/uscs/phenix/appointments/messaging/legacy/LegacyAppointmentClient.java',
    ],
    stack: ['Azure Service Bus', 'Spring Modulith', 'OpenFeign'],
  },
  {
    id: 'appt-migration-acl',
    archetype: 'cube',
    code: 'AM',
    name: 'Migration & sysid ACL',
    role: 'the identity bridge',
    group: 'appointments',
    whatItDoes:
      'Backfills the Postgres projection from legacy Oracle — appointments, docks, doors, notes, ' +
      'partner and product references, per warehouse — and owns the appointment sysid↔phenixId ' +
      'mapping table.',
    howItsBuilt:
      'A [[JDBC writer]] bulk-inserts migrated rows against explicit persistence records rather ' +
      'than JPA entities, keeping the copy fast and the mapping between the two schemas readable ' +
      'in one place.',
    files: [
      'phenix.appointments/src/main/java/com/uscs/phenix/appointments/migration/MigrationController.java',
      'phenix.appointments/src/main/java/com/uscs/phenix/appointments/migration/persistence/JdbcMigrationWriter.java',
      'phenix.appointments/src/main/java/com/uscs/phenix/appointments/acl/',
    ],
    stack: ['Spring JDBC', 'Oracle driver'],
  },
  {
    id: 'appt-db',
    archetype: 'low-slab',
    code: 'AD',
    name: 'Appointments Postgres',
    role: 'the v2 projection store',
    group: 'appointments',
    whatItDoes:
      'The v2 projection store: migrated appointment data, catalogs, id mappings and the durable ' +
      'event-publication registry.',
    howItsBuilt:
      'Flyway-owned like its yard sibling. The [[event_publication]] table (migration V2) is what ' +
      'lets the service promise "the v1 update will happen" the moment it consumes a bus message.',
    files: [
      'phenix.appointments/src/main/resources/db/migration/',
      'phenix.appointments/src/main/resources/application.yaml',
    ],
    stack: ['PostgreSQL', 'Flyway'],
  },
  {
    id: 'appt-tests',
    archetype: 'cube',
    code: 'AT',
    name: 'Test rig',
    role: 'the Testcontainers harness',
    group: 'appointments',
    whatItDoes:
      'Unit suites plus integration tests that boot the service against a Testcontainers Postgres ' +
      'to cover search, maintenance, messaging and migration end to end.',
    howItsBuilt:
      'Fast unit runs (mvnw test) are split from Docker-backed verification (mvnw verify), with ' +
      'JaCoCo coverage hanging off the same build — test ergonomics are treated as a first-class ' +
      'concern in the README.',
    files: ['phenix.appointments/src/test/java/com/uscs/phenix/appointments/'],
    stack: ['Testcontainers', 'JUnit', 'JaCoCo'],
  },

  /* ------------------------------------------------ Outside world & v1 */
  {
    id: 'uscs-v1',
    code: 'V1',
    name: 'USCS v1',
    role: 'the legacy estate',
    group: 'outside',
    whatItDoes:
      'The legacy estate, drawn as one building on purpose: the Angular front end (USCS-FE), the ' +
      'USCS-BE monolith and its Oracle database. Still the [[system of record]] for appointments, ' +
      'and the source every migration reads from.',
    howItsBuilt:
      'The v2 services touch it in exactly three ways — bulk Oracle reads during migration, live ' +
      'Oracle queries behind the appointments data-source toggle, and a purpose-built v1 adapter ' +
      'endpoint that accepts yard events back. Each path is designed to be deletable.',
    files: ['USCS-FE/', 'USCS-BE/'],
    stack: ['Angular', 'Java', 'Oracle'],
  },
  {
    id: 'keycloak',
    code: 'KC',
    name: 'Keycloak',
    role: 'the identity provider',
    group: 'outside',
    whatItDoes:
      'The identity provider. The UI redirects here to sign users in and returns with OIDC ' +
      'tokens; every backend call afterwards carries the resulting bearer token.',
    howItsBuilt:
      'The browser derives the Keycloak URL from its own origin, so one build serves every ' +
      'environment; realm and client id arrive as public environment variables.',
    files: ['phenix.ui/packages/auth/src/utils/keycloakConfig.ts'],
    stack: ['Keycloak', 'OIDC'],
  },
  {
    id: 'service-bus',
    code: 'SB',
    name: 'Azure Service Bus',
    role: 'the event backbone',
    group: 'outside',
    whatItDoes:
      'The event backbone between the services: the yard publishes gate events to the ' +
      '[[yard.events]] topic; the appointments service subscribes.',
    howItsBuilt:
      'Both sides treat the bus as optional infrastructure — the yard falls back to a logging ' +
      'broker and the listener stays quiet without a connection string — so the topic is additive ' +
      'to local development, never a prerequisite.',
    files: [
      'phenix.yard/src/main/java/com/uscs/phenix/yard/integration/event/ServiceBusYardEventBroker.java',
      'phenix.appointments/src/main/java/com/uscs/phenix/appointments/app/AzureServiceBusConfiguration.java',
    ],
    stack: ['Azure Service Bus', 'AMQP'],
  },
  {
    id: 'phenix-fleet',
    code: 'PF',
    name: 'Other Phenix services',
    role: 'the rest of the fleet',
    group: 'outside',
    archetype: 'fin-row',
    params: { count: 4 },
    whatItDoes:
      'The four platform services the UI talks to but this map does not open up: uaa-svc (user ' +
      'info), preferences-svc (preferences and feature flags), transaction-svc (activity history) ' +
      'and mapping-svc (warehouse master data and the warehouse ACL).',
    howItsBuilt:
      'All four are reached exclusively through the BFF’s generic passthrough — the browser ' +
      'never learns their addresses — and the yard service reuses mapping-svc server-side through ' +
      'a Feign client.',
    files: [
      'phenix.ui/apps/shell/src/app/ui-bff/serviceRegistry.ts',
      'phenix.yard/src/main/java/com/uscs/phenix/yard/warehouse/impl/WarehouseClient.java',
    ],
    stack: ['Spring Boot'],
  },
]

export const EDGES: ArchEdge[] = [
  /* browser → gateway */
  { id: 'e-yardapp-bff', from: 'ui-yard-app', to: 'ui-bff', kind: 'call', label: 'JSON over /ui-bff/yard/*', flowIds: ['arrival', 'overlook'] },
  { id: 'e-apptapp-bff', from: 'ui-appointments-app', to: 'ui-bff', kind: 'call', label: 'search + maintenance calls', flowIds: ['grid'] },
  { id: 'e-txapp-bff', from: 'ui-transaction-app', to: 'ui-bff', kind: 'call', label: 'activity queries', flowIds: ['txflow'] },
  { id: 'e-shell-bff', from: 'ui-shell', to: 'ui-bff', kind: 'call', label: 'admin + warehouse fetches', flowIds: ['migrate'] },
  { id: 'e-session-kc', from: 'ui-session-auth', to: 'keycloak', kind: 'call', label: 'OIDC redirect + token exchange', flowIds: ['signin'] },
  { id: 'e-session-bff', from: 'ui-session-auth', to: 'ui-bff', kind: 'call', label: 'session bootstrap fetches', flowIds: ['signin'] },
  { id: 'e-shell-kit', from: 'ui-shell', to: 'ui-kit', kind: 'support', label: 'renders through the kit', flowIds: [] },
  { id: 'e-yardapp-fe', from: 'ui-yard-app', to: 'ui-form-engine', kind: 'support', label: 'gate form schemas', flowIds: [] },

  /* gateway → services */
  { id: 'e-bff-yv2', from: 'ui-bff', to: 'yard-v2-api', kind: 'call', label: 'proxied REST /yard/*', flowIds: ['arrival', 'overlook'] },
  { id: 'e-bff-yseams', from: 'ui-bff', to: 'yard-seams', kind: 'call', label: 'appointment prefill lookup', flowIds: [] },
  { id: 'e-bff-ymig', from: 'ui-bff', to: 'yard-legacy-migration', kind: 'call', label: 'migration trigger + status', flowIds: ['migrate'] },
  { id: 'e-bff-appt', from: 'ui-bff', to: 'appt-api', kind: 'call', label: 'proxied REST appointments-svc', flowIds: ['grid'] },
  { id: 'e-bff-fleet', from: 'ui-bff', to: 'phenix-fleet', kind: 'call', label: 'uaa · preferences · transactions · mapping', flowIds: ['signin', 'txflow'] },

  /* yard internals */
  { id: 'e-yv2-core', from: 'yard-v2-api', to: 'yard-core', kind: 'call', label: 'adapters into yms helpers', flowIds: ['arrival', 'overlook'] },
  { id: 'e-seams-core', from: 'yard-seams', to: 'yard-core', kind: 'call', label: 'reads gate + trailer state', flowIds: [] },
  { id: 'e-core-ydb', from: 'yard-core', to: 'yard-db', kind: 'data', label: 'Hibernate reads/writes', flowIds: ['arrival', 'overlook'] },
  { id: 'e-core-events', from: 'yard-core', to: 'yard-events', kind: 'data', label: 'GateArrivalCompleted', flowIds: ['arrival'] },
  { id: 'e-events-bus', from: 'yard-events', to: 'service-bus', kind: 'call', label: 'publish to yard.events', flowIds: ['arrival'] },
  { id: 'e-yv2-fleet', from: 'yard-v2-api', to: 'phenix-fleet', kind: 'call', label: 'warehouse lookups via mapping-svc', flowIds: [] },
  { id: 'e-ymig-v1', from: 'yard-legacy-migration', to: 'uscs-v1', kind: 'data', label: 'Oracle rows over JDBC', flowIds: ['migrate'] },
  { id: 'e-ymig-ydb', from: 'yard-legacy-migration', to: 'yard-db', kind: 'data', label: 'migrated rows + ACL mappings', flowIds: ['migrate'] },

  /* events → appointments */
  { id: 'e-bus-apptev', from: 'service-bus', to: 'appt-events', kind: 'data', label: 'yard.events subscription', flowIds: ['arrival'] },
  { id: 'e-apptev-adb', from: 'appt-events', to: 'appt-db', kind: 'data', label: 'durable publications (Modulith)', flowIds: [] },
  { id: 'e-apptev-v1', from: 'appt-events', to: 'uscs-v1', kind: 'call', label: 'appointment PATCH to the v1 adapter', flowIds: ['arrival'] },

  /* appointments internals */
  { id: 'e-apptapi-adb', from: 'appt-api', to: 'appt-db', kind: 'data', label: 'Postgres projection queries', flowIds: ['grid'] },
  { id: 'e-apptapi-v1', from: 'appt-api', to: 'uscs-v1', kind: 'data', label: 'Oracle queries behind the toggle', flowIds: ['grid'] },
  { id: 'e-amig-v1', from: 'appt-migration-acl', to: 'uscs-v1', kind: 'data', label: 'bulk Oracle backfill reads', flowIds: [] },
  { id: 'e-amig-adb', from: 'appt-migration-acl', to: 'appt-db', kind: 'data', label: 'projection + id mappings', flowIds: [] },

  /* test rigs */
  { id: 'e-ytests-yv2', from: 'yard-tests', to: 'yard-v2-api', kind: 'support', label: 'Cucumber drives HTTP', flowIds: [] },
  { id: 'e-atests-api', from: 'appt-tests', to: 'appt-api', kind: 'support', label: 'Testcontainers HTTP + SQL', flowIds: [] },
]

export const FLOWS: ArchFlow[] = [
  {
    id: 'signin',
    name: 'Sign in',
    payload: 'OIDC tokens',
    summary:
      'From the auth gate through Keycloak and back: tokens land in sessionStorage, then the ' +
      'bootstrap pulls user info, feature flags and preferences through the BFF.',
    route: ['e-session-kc', 'e-session-bff', 'e-bff-fleet'],
  },
  {
    id: 'arrival',
    name: 'Gate arrival',
    payload: 'trailer arrival',
    summary:
      'A trailer checks in and the fact fans out: yard Postgres first, then a GateArrivalCompleted ' +
      'event crosses the bus and ends as an appointment update inside v1.',
    route: [
      'e-yardapp-bff',
      'e-bff-yv2',
      'e-yv2-core',
      'e-core-ydb',
      'e-core-events',
      'e-events-bus',
      'e-bus-apptev',
      'e-apptev-v1',
    ],
  },
  {
    id: 'overlook',
    name: 'Yard overlook',
    payload: 'yard snapshot',
    summary:
      'The overlook map asks for the whole yard in one snapshot — areas, spots and trailers, ' +
      'served straight out of the lifted core’s state.',
    route: ['e-yardapp-bff', 'e-bff-yv2', 'e-yv2-core', 'e-core-ydb'],
  },
  {
    id: 'grid',
    name: 'Appointments grid',
    payload: 'search page',
    summary:
      'The maintenance grid searches appointments; per warehouse, the data-source toggle decides ' +
      'whether the page comes from the Postgres projection or live legacy Oracle.',
    route: ['e-apptapp-bff', 'e-bff-appt', 'e-apptapi-adb', 'e-apptapi-v1'],
  },
  {
    id: 'migrate',
    name: 'Warehouse migration',
    payload: 'Oracle rows',
    summary:
      'An admin presses migrate: the orchestrator reads one warehouse’s yard world out of v1 ' +
      'Oracle and writes rows plus sysid↔phenixId mappings into yard Postgres.',
    route: ['e-shell-bff', 'e-bff-ymig', 'e-ymig-v1', 'e-ymig-ydb'],
  },
  {
    id: 'txflow',
    name: 'Transaction history',
    payload: 'activity page',
    summary:
      'The first sub-app at work: activity queries pass through the BFF to transaction-svc like ' +
      'every other backend call.',
    route: ['e-txapp-bff', 'e-bff-fleet'],
  },
]

const INTRO = {
  title: 'The Phenix platform',
  lede:
    'Three repositories drawn as one city: the phenix.ui monorepo up front, the two Spring ' +
    'services behind it, and the v1 estate they are all slowly draining.',
  whatItDoes:
    'Phenix is US Cold Storage’s warehouse platform, rebuilt screen by screen. One Next.js ' +
    'shell serves four sub-apps; a BFF gateway is the only door to the backends; the yard and ' +
    'appointments services own their domains in Postgres while the legacy Angular-and-Oracle ' +
    'world keeps running as the single grey building across the street.',
  howItsBuilt:
    'The recurring pattern is the strangler seam: v1 code lifted as-is behind new REST faces, a ' +
    'sysid↔phenixId ACL at every identity boundary, events over Service Bus instead of shared ' +
    'tables, and per-warehouse migrations moving truth from Oracle to Postgres one table at a time.',
}

/* ---------------------------------------------- derived geometry + merge */

const measureOf = (id: string) => MEASURED[id] ?? { count: 0, loc: 0 }

const sized = AUTHORED.map((node) => {
  const measure = measureOf(node.id)
  const derived = deriveArchetype(measure)
  const archetype = node.archetype ?? derived.archetype
  // Derived params only fit the derived shape — an authored override supplies its own.
  const params = node.params ?? (archetype === derived.archetype ? derived.params : undefined)
  return { node, archetype, params, size: deriveSize(archetype, params, measure) }
})

const footprints = packLayout(
  sized.map(({ node, size }) => ({ item: node.id, group: node.group, size })),
  GROUPS.map((g) => g.id),
)

export const NODES: ArchNode[] = sized.map(({ node, archetype, params }) => {
  const measure = measureOf(node.id)
  return {
    ...node,
    archetype,
    params,
    height: node.height ?? deriveHeight(measure),
    footprint: node.footprint ?? footprints.get(node.id)!,
    count: measure.count,
    loc: measure.loc,
  }
})

export const ARCHITECTURE: ArchitectureData = {
  groups: GROUPS,
  nodes: NODES,
  edges: EDGES,
  flows: FLOWS,
  intro: INTRO,
  unmapped: UNCLAIMED,
  repo: 'uscold — phenix.ui · phenix.yard · phenix.appointments',
}
