/**
 * @generated by scripts/architecture-sync.mjs — do not edit.
 *
 * Measured from the tree, so the map's numbers cannot drift from the code.
 * `UNCLAIMED` is what no module on the map covers: run the sync script, then
 * either give an existing module a wider pattern in coverage.json or add the
 * node the repo has been missing.
 */

export const MEASURED: Record<string, { count: number; loc: number }> = {
  'appt-api': { count: 108, loc: 8386 },
  'appt-db': { count: 21, loc: 665 },
  'appt-events': { count: 27, loc: 1116 },
  'appt-migration-acl': { count: 30, loc: 2275 },
  'appt-tests': { count: 53, loc: 9736 },
  'ui-appointments-app': { count: 63, loc: 9952 },
  'ui-bff': { count: 21, loc: 2527 },
  'ui-form-engine': { count: 91, loc: 11834 },
  'ui-kit': { count: 226, loc: 28210 },
  'ui-session-auth': { count: 106, loc: 9664 },
  'ui-shell': { count: 120, loc: 6073 },
  'ui-transaction-app': { count: 220, loc: 30487 },
  'ui-workshop': { count: 51, loc: 5109 },
  'ui-yard-app': { count: 269, loc: 30506 },
  'yard-core': { count: 279, loc: 30845 },
  'yard-db': { count: 11, loc: 1067 },
  'yard-events': { count: 15, loc: 562 },
  'yard-legacy-migration': { count: 85, loc: 4176 },
  'yard-seams': { count: 147, loc: 3586 },
  'yard-tests': { count: 170, loc: 20523 },
  'yard-v2-api': { count: 121, loc: 10186 },
}

export const UNCLAIMED: string[] = []
